// Generated by Tools/gen_chuck_clip_data.py from
// SourceAssets/Chuck/V1/Animations/manifest.json. Do not edit by hand.
#pragma once

namespace ChuckClipData
{
    // WalkLoop: distance-matched saunter (manifest reference speed, cycle, stance).
    constexpr float WalkSpeed = 72.0000f;
    constexpr float WalkPeriod = 0.4667f;
    constexpr float WalkStride = 33.6000f;
    constexpr float StanceFraction = 0.6000f;
    // RunLoop: same phase convention as WalkLoop; the runtime blends them by speed.
    constexpr float RunSpeed = 225.0000f;
    constexpr float RunPeriod = 0.3333f;
    constexpr float RunStride = 75.0000f;
    constexpr float RunStanceFraction = 0.3000f;
    constexpr float RunJumpVerticalSpeed = 190.0000f;  // leap out of a run
    // SprintLoop: the four-legged burst; phase 0 = foot_L touchdown, foot_R SprintHindLag later.
    constexpr float SprintSpeed = 380.0000f;
    constexpr float SprintPeriod = 0.2667f;
    constexpr float SprintStride = 101.3330f;
    constexpr float SprintStanceFraction = 0.2500f;
    constexpr float SprintHindLag = 0.0700f;
    constexpr float SprintLeapVerticalSpeed = 250.0000f;  // leap out of the sprint
    constexpr float SprintLeapSpeed = 420.0000f;  // its push-off along the ground
    constexpr float SprintForeLand = 0.4400f;  // the leap lands on the forepaws here in the stride
    // WalkStart/WalkStop: smoothstep speed ramps over Duration covering Travel cm.
    constexpr float StartDuration = 0.5000f;
    constexpr float StartTravel = 18.0000f;
    constexpr float StopDuration = 0.5000f;
    constexpr float StopTravel = 18.0000f;

    // Stance windows (s): foot_L spans, foot_R spans (lift/plant pairs, -1 padded), clip end.
    struct FStance { float L[6]; float R[6]; float End; };
    constexpr FStance StartStance{{0.0000f, 0.3133f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0000f, 0.0800f, 0.2667f, 0.5000f, -1.0000f, -1.0000f}, 0.5000f};
    constexpr FStance StopStance{{0.0000f, 0.2800f, 0.5067f, 0.6000f, -1.0000f, -1.0000f}, {0.0000f, 0.0467f, 0.2633f, 0.6000f, -1.0000f, -1.0000f}, 0.6000f};
    constexpr FStance StopStanceMirrored{{0.0000f, 0.0467f, 0.2633f, 0.6000f, -1.0000f, -1.0000f}, {0.0000f, 0.2800f, 0.5067f, 0.6000f, -1.0000f, -1.0000f}, 0.6000f};
    constexpr FStance TurnLeftStance{{0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, {0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, 0.6667f};
    constexpr FStance TurnRightStance{{0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, {0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, 0.6667f};

    // Turn in place: capsule yaw magnitude (deg) per 30 fps frame until it settles.
    constexpr float TurnYaw[] = {0.0000f, 0.2045f, 2.3867f, 6.6667f, 12.6828f, 20.0733f, 28.4766f, 37.5309f, 46.8745f, 56.1458f, 64.9831f, 73.0247f, 79.9089f, 85.2739f, 88.7582f, 90.0000f};
    constexpr int TurnYawFrames = 15;
    constexpr float TurnEnd = 0.5500f;  // just after the last plant

    // Roll: capsule travel (cm) per 30 fps frame along the facing direction.
    constexpr float RollTravel[] = {0.0000f, 0.6641f, 4.2475f, 10.7500f, 17.9167f, 25.0833f, 32.2500f, 39.4167f, 46.5833f, 53.7500f, 60.9167f, 68.0833f, 75.2500f, 82.4043f, 89.1006f, 94.5483f, 98.3089f, 100.3431f, 101.0091f, 101.0500f, 101.0500f, 101.0500f, 101.0500f, 101.0500f, 101.0500f};
    constexpr int RollFrames = 24;
    constexpr FStance RollStance{{0.0000f, 0.0800f, 0.5600f, 0.8000f, -1.0000f, -1.0000f}, {0.0000f, 0.0800f, 0.5600f, 0.8000f, -1.0000f, -1.0000f}, 0.8000f};
    constexpr float RollPlant = 0.5600f;  // paws back on the ground
    // Slash (claw scratch): capsule travel per 30 fps frame (standing), chain window, stance.
    constexpr float SlashTravel[] = {0.0000f, 0.0000f, 0.3293f, 1.7706f, 3.9736f, 6.5151f, 8.9719f, 10.9210f, 11.9392f, 12.0000f, 12.0000f, 12.0000f, 12.0000f};
    constexpr int SlashFrames = 12;
    constexpr float SlashChainAt = 0.2182f;
    constexpr float SlashStrike = 0.1600f;  // the cut: what it hits breaks here
    constexpr FStance SlashRightStance{{0.0000f, 0.0436f, 0.1600f, 0.4000f, -1.0000f, -1.0000f}, {0.0000f, 0.2036f, 0.3055f, 0.4000f, -1.0000f, -1.0000f}, 0.4000f};
    constexpr FStance SlashLeftStance{{0.0000f, 0.2036f, 0.3055f, 0.4000f, -1.0000f, -1.0000f}, {0.0000f, 0.0436f, 0.1600f, 0.4000f, -1.0000f, -1.0000f}, 0.4000f};
    // Wall run: loop phase follows the vertical capsule travel over this stride.
    constexpr float WallRunStride = 30.0000f;
    // Ledges: hang depth, and the capsule path (forward, up) per 30 fps frame of PullUp and Mantle.
    constexpr float HangDrop = 22.0000f;
    constexpr float ShimmyStride = 16.0000f;
    // Brachiation: the ring in mesh space (forward, up from the capsule bottom), the swing angle at the clip ends, and where the leap starts and ends on that scale.
    constexpr float SwingGripX = 5.5000f;
    constexpr float SwingGripZ = 63.5000f;
    constexpr float SwingMaxAngle = 40.0000f;
    constexpr float SwingRelease = 0.7500f;
    constexpr float SwingCatch = -0.6250f;
    constexpr float PullUpPath[][2] = {{0.0000f, 0.0000f}, {0.0000f, 0.0000f}, {0.0000f, 0.2187f}, {0.0000f, 1.8690f}, {0.0000f, 4.9148f}, {0.0000f, 9.0903f}, {0.0000f, 14.1296f}, {0.6690f, 19.7671f}, {2.5185f, 25.7368f}, {5.3125f, 31.7730f}, {8.8148f, 37.6098f}, {12.7894f, 42.9814f}, {17.0000f, 47.6221f}, {21.2106f, 51.2659f}, {25.1852f, 53.6472f}, {28.6875f, 54.5000f}, {31.4815f, 54.5000f}, {33.3310f, 54.5000f}, {34.0000f, 54.5000f}, {34.0000f, 54.5000f}, {34.0000f, 54.5000f}, {34.0000f, 54.5000f}};
    constexpr int PullUpFrames = 21;
    constexpr float PullUpRise = 54.5000f;
    constexpr float PullUpAdvance = 34.0000f;
    constexpr float MantlePath[][2] = {{0.0000f, 0.0000f}, {0.0000f, 0.0000f}, {0.0000f, 0.4919f}, {0.5089f, 3.9062f}, {3.2792f, 9.4039f}, {7.7619f, 15.5961f}, {13.1604f, 21.0938f}, {18.6785f, 24.5081f}, {23.5195f, 25.0000f}, {26.8872f, 25.0000f}, {28.0000f, 25.0000f}};
    constexpr int MantleFrames = 10;
    constexpr float MantleRefStep = 25.0000f;
    constexpr float MantleAdvance = 28.0000f;
    // Speed vault: the clearance over the top and the capsule path's plateau (fraction of progress up, down).
    constexpr float VaultClear = 6.0000f;
    constexpr float VaultDuration = 0.5000f;
    // Side jump: sideways launch at takeoff; the clip holds just before land while airborne.
    constexpr float SideTakeoff = 0.1000f;
    constexpr float SideLand = 0.5000f;
    constexpr float SideLateralSpeed = 190.0000f;
    constexpr float SideVerticalSpeed = 158.3920f;
    constexpr FStance SideJumpStance{{0.0000f, 0.1000f, 0.5000f, 0.8000f, -1.0000f, -1.0000f}, {0.0000f, 0.1000f, 0.5000f, 0.8000f, -1.0000f, -1.0000f}, 0.8000f};
    // Side jump length follows the run latch (user 2026-09-29): short from a walk, long from a run.
    constexpr float SideShortLateralSpeed = 150.0000f;
    constexpr float SideShortVerticalSpeed = 142.7730f;
    constexpr float SideLongLateralSpeed = 265.0000f;
    constexpr float SideLongVerticalSpeed = 185.7310f;
    // Strafe (sidestep / bounding shuffle): loop phase follows sideways travel over the stride.
    constexpr float StrafeSpeed = 55.0000f;
    constexpr float StrafeStride = 22.0000f;
    constexpr float StrafeRunSpeed = 150.0000f;
    constexpr float StrafeRunStride = 50.0000f;
    constexpr FStance StrafeLeftStance{{0.0000f, 0.2600f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.1400f, 0.4000f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, 0.4000f};
    constexpr FStance StrafeRightStance{{0.1400f, 0.4000f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0000f, 0.2600f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, 0.4000f};
    constexpr FStance StrafeRunLeftStance{{0.0000f, 0.1000f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0500f, 0.1500f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, 0.3333f};
    constexpr FStance StrafeRunRightStance{{0.0500f, 0.1500f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0000f, 0.1000f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, 0.3333f};
}
