// Generated by Tools/gen_chuck_clip_data.py from
// SourceAssets/Chuck/V1/Animations/manifest.json. Do not edit by hand.
#pragma once

namespace ChuckClipData
{
    // WalkLoop: distance-matched saunter (manifest reference speed, cycle, stance).
    constexpr float WalkSpeed = 62.0000f;
    constexpr float WalkPeriod = 0.5000f;
    constexpr float WalkStride = 31.0000f;
    constexpr float StanceFraction = 0.6200f;
    // WalkStart/WalkStop: smoothstep speed ramps over Duration covering Travel cm.
    constexpr float StartDuration = 0.5000f;
    constexpr float StartTravel = 15.5000f;
    constexpr float StopDuration = 0.5000f;
    constexpr float StopTravel = 15.5000f;

    // Stance windows (s): foot_L spans, foot_R spans (lift/plant pairs, -1 padded), clip end.
    struct FStance { float L[6]; float R[6]; float End; };
    constexpr FStance StartStance{{0.0000f, 0.3100f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0000f, 0.0800f, 0.2700f, 0.5000f, -1.0000f, -1.0000f}, 0.5000f};
    constexpr FStance StopStance{{0.0000f, 0.3100f, 0.5400f, 0.6333f, -1.0000f, -1.0000f}, {0.0000f, 0.0600f, 0.2800f, 0.6333f, -1.0000f, -1.0000f}, 0.6333f};
    constexpr FStance StopStanceMirrored{{0.0000f, 0.0600f, 0.2800f, 0.6333f, -1.0000f, -1.0000f}, {0.0000f, 0.3100f, 0.5400f, 0.6333f, -1.0000f, -1.0000f}, 0.6333f};
    constexpr FStance TurnLeftStance{{0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, {0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, 0.6667f};
    constexpr FStance TurnRightStance{{0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, {0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, 0.6667f};

    // Turn in place: capsule yaw magnitude (deg) per 30 fps frame until it settles.
    constexpr float TurnYaw[] = {0.0000f, 0.2045f, 2.3867f, 6.6667f, 12.6828f, 20.0733f, 28.4766f, 37.5309f, 46.8745f, 56.1458f, 64.9831f, 73.0247f, 79.9089f, 85.2739f, 88.7582f, 90.0000f};
    constexpr int TurnYawFrames = 15;
    constexpr float TurnEnd = 0.5500f;  // just after the last plant
}
