// Generated by Tools/gen_chuck_clip_data.py from
// SourceAssets/Chuck/V1/Animations/manifest.json. Do not edit by hand.
#pragma once

namespace ChuckClipData
{
    // WalkLoop: distance-matched saunter (manifest reference speed, cycle, stance).
    constexpr float WalkSpeed = 72.0000f;
    constexpr float WalkPeriod = 0.4667f;
    constexpr float WalkStride = 33.6000f;
    constexpr float StanceFraction = 0.6000f;
    // RunLoop: same phase convention as WalkLoop; the runtime blends them by speed.
    constexpr float RunSpeed = 190.0000f;
    constexpr float RunPeriod = 0.4000f;
    constexpr float RunStride = 76.0000f;
    constexpr float RunStanceFraction = 0.3000f;
    constexpr float RunJumpVerticalSpeed = 190.0000f;  // leap out of a run
    // WalkStart/WalkStop: smoothstep speed ramps over Duration covering Travel cm.
    constexpr float StartDuration = 0.5000f;
    constexpr float StartTravel = 18.0000f;
    constexpr float StopDuration = 0.5000f;
    constexpr float StopTravel = 18.0000f;

    // Stance windows (s): foot_L spans, foot_R spans (lift/plant pairs, -1 padded), clip end.
    struct FStance { float L[6]; float R[6]; float End; };
    constexpr FStance StartStance{{0.0000f, 0.3133f, -1.0000f, -1.0000f, -1.0000f, -1.0000f}, {0.0000f, 0.0800f, 0.2667f, 0.5000f, -1.0000f, -1.0000f}, 0.5000f};
    constexpr FStance StopStance{{0.0000f, 0.2800f, 0.5067f, 0.6000f, -1.0000f, -1.0000f}, {0.0000f, 0.0467f, 0.2633f, 0.6000f, -1.0000f, -1.0000f}, 0.6000f};
    constexpr FStance StopStanceMirrored{{0.0000f, 0.0467f, 0.2633f, 0.6000f, -1.0000f, -1.0000f}, {0.0000f, 0.2800f, 0.5067f, 0.6000f, -1.0000f, -1.0000f}, 0.6000f};
    constexpr FStance TurnLeftStance{{0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, {0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, 0.6667f};
    constexpr FStance TurnRightStance{{0.0000f, 0.2000f, 0.3600f, 0.6667f, -1.0000f, -1.0000f}, {0.0000f, 0.0400f, 0.2000f, 0.3600f, 0.5200f, 0.6667f}, 0.6667f};

    // Turn in place: capsule yaw magnitude (deg) per 30 fps frame until it settles.
    constexpr float TurnYaw[] = {0.0000f, 0.2045f, 2.3867f, 6.6667f, 12.6828f, 20.0733f, 28.4766f, 37.5309f, 46.8745f, 56.1458f, 64.9831f, 73.0247f, 79.9089f, 85.2739f, 88.7582f, 90.0000f};
    constexpr int TurnYawFrames = 15;
    constexpr float TurnEnd = 0.5500f;  // just after the last plant

    // Roll: capsule travel (cm) per 30 fps frame along the facing direction.
    constexpr float RollTravel[] = {0.0000f, 0.6641f, 4.2475f, 10.7500f, 17.9167f, 25.0833f, 32.2500f, 39.4167f, 46.5833f, 53.7500f, 60.9167f, 68.0833f, 75.2500f, 82.4043f, 89.1006f, 94.5483f, 98.3089f, 100.3431f, 101.0091f, 101.0500f, 101.0500f, 101.0500f, 101.0500f, 101.0500f, 101.0500f};
    constexpr int RollFrames = 24;
    constexpr FStance RollStance{{0.0000f, 0.0800f, 0.5600f, 0.8000f, -1.0000f, -1.0000f}, {0.0000f, 0.0800f, 0.5600f, 0.8000f, -1.0000f, -1.0000f}, 0.8000f};
    constexpr float RollPlant = 0.5600f;  // paws back on the ground
    // Slash (claw scratch): capsule travel per 30 fps frame (standing), chain window, stance.
    constexpr float SlashTravel[] = {0.0000f, 0.0000f, 0.0154f, 0.5156f, 1.6018f, 3.1111f, 4.8809f, 6.7483f, 8.5506f, 10.1250f, 11.3088f, 11.9392f, 12.0000f, 12.0000f, 12.0000f, 12.0000f, 12.0000f};
    constexpr int SlashFrames = 16;
    constexpr float SlashChainAt = 0.3000f;
    constexpr FStance SlashRightStance{{0.0000f, 0.0600f, 0.2200f, 0.5500f, -1.0000f, -1.0000f}, {0.0000f, 0.2800f, 0.4200f, 0.5500f, -1.0000f, -1.0000f}, 0.5333f};
    constexpr FStance SlashLeftStance{{0.0000f, 0.2800f, 0.4200f, 0.5500f, -1.0000f, -1.0000f}, {0.0000f, 0.0600f, 0.2200f, 0.5500f, -1.0000f, -1.0000f}, 0.5333f};
    // Side jump: sideways launch at takeoff; the clip holds just before land while airborne.
    constexpr float SideTakeoff = 0.1000f;
    constexpr float SideLand = 0.5000f;
    constexpr float SideLateralSpeed = 190.0000f;
    constexpr float SideVerticalSpeed = 158.3920f;
    constexpr FStance SideJumpStance{{0.0000f, 0.1000f, 0.5000f, 0.8000f, -1.0000f, -1.0000f}, {0.0000f, 0.1000f, 0.5000f, 0.8000f, -1.0000f, -1.0000f}, 0.8000f};
}
