// Generated by Tools/build_clay_jar.py. Do not edit by hand.
#pragma once

namespace ClayJarData
{
    constexpr float Height = 25.5000f;
    constexpr float Radius = 9.6000f;   // widest (the belly)
    constexpr int ShardCount = 12;
    // Each shard mesh's rest offset from the jar origin (its centre), cm.
    constexpr float ShardOffset[][3] = {{4.9550f, -4.1030f, 4.3990f}, {4.1060f, 4.9720f, 4.3980f}, {-4.9690f, 4.1260f, 4.4010f}, {-4.1270f, -4.9570f, 4.4020f}, {-6.9060f, -2.9640f, 12.2420f}, {0.7080f, -7.5160f, 12.2470f}, {7.3670f, -1.6830f, 12.2620f}, {3.8540f, 6.4610f, 12.2330f}, {-4.9740f, 5.6980f, 12.2650f}, {1.8250f, 3.6420f, 21.0090f}, {-4.0590f, -0.2440f, 20.9990f}, {2.2470f, -3.4030f, 20.9930f}};
}
