"""Blender 4.5.14 (its aud module and numpy): NPC voice lines from SourceAssets/NPCs/dialogue.json
(docs/NPC-VOICE-PLAN.md; user 2026-10-05: the dwarf's ElevenLabs line).

blender --background --factory-startup --python Tools/build_npc_voice.py
  -> SourceAssets/NPCs/Voice/<NPC>/<id>.wav            44.1 kHz mono 16-bit, trimmed to the line, faded in/out 10 ms
     SourceAssets/NPCs/Voice/manifest.json               per line: wav, seconds, peaks
     Unreal/Chuck3D/Source/Chuck3D/NPCVoiceData.h        per line: text, sound asset path, loudness envelope

The envelope is the line's own loudness at 60 frames a second (RMS over 30 ms,
divided by its 95th percentile, clipped to 1, as 0..255): ADockNPC opens the
jaw, lifts the brows and nods with it while the line plays. (Rhubarb mouth
shapes, phase 2 of the plan, can replace it for NPCs whose mouths show; the
dwarf's beard hides his lips.)
"""
from pathlib import Path
import json
import wave
import aud
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
NPCS = ROOT / 'SourceAssets/NPCs'
OUT_H = ROOT / 'Unreal/Chuck3D/Source/Chuck3D/NPCVoiceData.h'
FPS = 60
SPEC = json.loads((NPCS / 'dialogue.json').read_text(encoding='utf-8'))['npcs']


def decode(path):
    s = aud.Sound(str(path))
    rate = int(s.specs[0])
    a = s.data()
    return (a.mean(axis=1) if a.ndim > 1 else a).astype(np.float64), rate


def envelope(x, rate):
    hop, win = rate // FPS, int(rate * .03)
    rms = np.sqrt(np.convolve(x * x, np.ones(win) / win, 'same'))[::hop]
    ref = np.percentile(rms[rms > rms.max() * .05], 95) if (rms > rms.max() * .05).any() else rms.max()
    return np.clip(rms / max(ref, 1e-6), 0, 1)


manifest, entries = {'generator': 'Tools/build_npc_voice.py', 'lines': {}}, []
for npc, spec in SPEC.items():
    for line in spec.get('talk', []):
        x, rate = decode(NPCS / line['source'])
        x = x[int(line.get('start', 0) * rate):int(line.get('end', len(x) / rate) * rate)]
        fade = int(rate * .01)
        x[:fade] *= np.linspace(0, 1, fade); x[-fade:] *= np.linspace(1, 0, fade)
        dst = NPCS / 'Voice' / npc / f"{line['id']}.wav"
        dst.parent.mkdir(parents=True, exist_ok=True)
        with wave.open(str(dst), 'wb') as w:
            w.setnchannels(1); w.setsampwidth(2); w.setframerate(rate)
            w.writeframes((np.clip(x, -1, 1) * 32767).astype('<i2').tobytes())
        env = envelope(x, rate)
        q = np.round(env * 255).astype(int)
        peaks = int(((env[1:-1] > env[:-2]) & (env[1:-1] >= env[2:]) & (env[1:-1] > .6)).sum())
        asset = f"/Game/Art/Audio/Voice/{npc}/VO_{npc}_{line['id']}"
        manifest['lines'][f"{npc}/{line['id']}"] = {'wav': dst.relative_to(NPCS).as_posix(), 'asset': asset,
                                                     'seconds': round(len(x) / rate, 3), 'rate': rate, 'peaks': peaks}
        entries.append((npc, line, asset, q, len(x) / rate))
        print('CHUCK_VOICE_LINE', npc, line['id'], f'seconds={len(x) / rate:.2f}', f'frames={len(q)}', f'peaks={peaks}')
(NPCS / 'Voice/manifest.json').write_text(json.dumps(manifest, indent=1) + '\n', encoding='utf-8')
BS = chr(92)   # backslash
cpp = lambda t: ''.join(BS + BS if ch == BS else BS + '"' if ch == '"' else ch if ord(ch) < 128 else f'{BS}u{ord(ch):04x}' for ch in t)   # ASCII-only C++ literal
lines = ['// Generated by Tools/build_npc_voice.py from SourceAssets/NPCs/dialogue.json. Do not edit by hand.', '#pragma once', '',
         'namespace NPCVoiceData', '{', f'    constexpr float EnvelopeRate = {FPS}.f;   // envelope frames per second',
         '    struct FLine { const TCHAR* Npc; const TCHAR* Id; const TCHAR* Text; const TCHAR* Sound; float Seconds; const uint8* Envelope; int32 Frames; };']
for k, (npc, line, asset, q, secs) in enumerate(entries):
    lines.append(f'    constexpr uint8 Envelope{k}[] = {{{", ".join(str(v) for v in q)}}};')
lines.append('    const FLine Lines[] = {')
for k, (npc, line, asset, q, secs) in enumerate(entries):
    lines.append(f'        {{ TEXT("{npc}"), TEXT("{line["id"]}"), TEXT("{cpp(line["text"])}"), TEXT("{asset}.VO_{npc}_{line["id"]}"), {secs:.3f}f, Envelope{k}, {len(q)} }},')
lines += ['    };', '    constexpr int32 LineCount = UE_ARRAY_COUNT(Lines);', '}', '']
OUT_H.write_text('\n'.join(lines), encoding='utf-8')
print('CHUCK_VOICE_READY', len(entries))
