"""Write Unreal/Chuck3D/Source/Chuck3D/ChuckClipData.h from the v1 clip manifest.

python Tools/gen_chuck_clip_data.py   (also run by Tools/build_chuck_v1.py)

The runtime (ChuckCharacter.cpp) distance-matches WalkStart/WalkLoop/WalkStop,
locks paws in the manifest stance windows and drives turn-in-place yaw from the
authored profile. Generating those numbers keeps the game in step with the
clips whenever the walk is re-authored (e.g. the 2026-09-27 saunter).
Pure Python; no Blender or Unreal needed.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'SourceAssets/Chuck/V1/Animations/manifest.json'
OUT = ROOT / 'Unreal/Chuck3D/Source/Chuck3D/ChuckClipData.h'


def f(v):
    return f'{v:.4f}f'


def stance(clip, mirror=False):
    """FStance initializer: up to three [lift, plant] spans per paw, -1 padded."""
    si = clip['stance_intervals_s']
    left, right = si['foot_L'], si['foot_R']
    if mirror:
        left, right = right, left
    def side(spans):
        flat = [v for span in spans for v in span][:6]
        flat += [-1.] * (6 - len(flat))
        return '{' + ', '.join(f(v) for v in flat) + '}'
    end = clip['duration_s']
    return f'{{{side(left)}, {side(right)}, {f(end)}}}'


def main():
    m = json.loads(MANIFEST.read_text(encoding='utf-8'))
    clips = {c['name']: c for c in m['clips']}
    walk, start, stop = clips['WalkLoop'], clips['WalkStart'], clips['WalkStop']
    turn = clips['TurnLeft90']
    roll, side = clips['Roll'], clips['SideJumpLeft']
    run = clips['RunLoop']
    slash = clips['SlashRight']
    wall = clips['WallRun']
    strafe, strafe_run = clips['StrafeLeft'], clips['StrafeRunLeft']
    hang, pull, mantle = clips['Hang'], clips['PullUp'], clips['Mantle']
    yaw = [abs(v) for v in turn['capsule_yaw_deg_per_frame']]
    # Frames until the yaw reaches its final value; the tail is the settle hold.
    last = next(i for i, v in enumerate(yaw) if abs(v - yaw[-1]) < 1e-3)
    turn_end = max(t for k, t in turn['events_s'].items() if 'plant' in k) + .03
    lines = [
        '// Generated by Tools/gen_chuck_clip_data.py from',
        '// SourceAssets/Chuck/V1/Animations/manifest.json. Do not edit by hand.',
        '#pragma once',
        '',
        'namespace ChuckClipData',
        '{',
        '    // WalkLoop: distance-matched saunter (manifest reference speed, cycle, stance).',
        f"    constexpr float WalkSpeed = {f(walk['reference_speed_cm_s'])};",
        f"    constexpr float WalkPeriod = {f(walk['duration_s'])};",
        f"    constexpr float WalkStride = {f(walk['stride_cycle_cm'])};",
        f"    constexpr float StanceFraction = {f(walk['stance_fraction'])};",
        '    // RunLoop: same phase convention as WalkLoop; the runtime blends them by speed.',
        f"    constexpr float RunSpeed = {f(run['reference_speed_cm_s'])};",
        f"    constexpr float RunPeriod = {f(run['duration_s'])};",
        f"    constexpr float RunStride = {f(run['stride_cycle_cm'])};",
        f"    constexpr float RunStanceFraction = {f(run['stance_fraction'])};",
        f"    constexpr float RunJumpVerticalSpeed = {f(clips['RunJump']['launch']['vertical_cm_s'])};  // leap out of a run",
        '    // WalkStart/WalkStop: smoothstep speed ramps over Duration covering Travel cm.',
        f"    constexpr float StartDuration = {f(start['duration_travel_s'])};",
        f"    constexpr float StartTravel = {f(start['travel_cm'])};",
        f"    constexpr float StopDuration = {f(stop['duration_travel_s'])};",
        f"    constexpr float StopTravel = {f(stop['travel_cm'])};",
        '',
        '    // Stance windows (s): foot_L spans, foot_R spans (lift/plant pairs, -1 padded), clip end.',
        '    struct FStance { float L[6]; float R[6]; float End; };',
        f"    constexpr FStance StartStance{stance(start)};",
        f"    constexpr FStance StopStance{stance(stop)};",
        f"    constexpr FStance StopStanceMirrored{stance(stop, True)};",
        f"    constexpr FStance TurnLeftStance{stance(turn)};",
        f"    constexpr FStance TurnRightStance{stance(clips['TurnRight90'])};",
        '',
        '    // Turn in place: capsule yaw magnitude (deg) per 30 fps frame until it settles.',
        '    constexpr float TurnYaw[] = {' + ', '.join(f(v) for v in yaw[:last + 1]) + '};',
        f'    constexpr int TurnYawFrames = {last};',
        f'    constexpr float TurnEnd = {f(turn_end)};  // just after the last plant',
        '',
        '    // Roll: capsule travel (cm) per 30 fps frame along the facing direction.',
        '    constexpr float RollTravel[] = {' + ', '.join(f(v) for v in roll['capsule_travel_cm_per_frame']) + '};',
        f"    constexpr int RollFrames = {len(roll['capsule_travel_cm_per_frame']) - 1};",
        f"    constexpr FStance RollStance{stance(roll)};",
        f"    constexpr float RollPlant = {f(roll['events_s']['plant'])};  // paws back on the ground",
        '    // Slash (claw scratch): capsule travel per 30 fps frame (standing), chain window, stance.',
        '    constexpr float SlashTravel[] = {' + ', '.join(f(v) for v in slash['capsule_travel_cm_per_frame']) + '};',
        f"    constexpr int SlashFrames = {len(slash['capsule_travel_cm_per_frame']) - 1};",
        f"    constexpr float SlashChainAt = {f(slash['events_s']['chain_from'])};",
        f"    constexpr FStance SlashRightStance{stance(slash)};",
        f"    constexpr FStance SlashLeftStance{stance(clips['SlashLeft'])};",
        '    // Wall run: loop phase follows the vertical capsule travel over this stride.',
        f"    constexpr float WallRunStride = {f(wall['stride_cycle_cm'])};",
        '    // Ledges: hang depth, and the capsule path (forward, up) per 30 fps frame of PullUp and Mantle.',
        f"    constexpr float HangDrop = {f(hang['hang_drop_cm'])};",
        f"    constexpr float ShimmyStride = {f(clips['ShimmyLeft']['stride_cycle_cm'])};",
        '    constexpr float PullUpPath[][2] = {' + ', '.join('{' + f(a) + ', ' + f(b) + '}' for a, b in pull['capsule_path_cm_per_frame']) + '};',
        f"    constexpr int PullUpFrames = {len(pull['capsule_path_cm_per_frame']) - 1};",
        f"    constexpr float PullUpRise = {f(pull['rise_cm'])};",
        f"    constexpr float PullUpAdvance = {f(pull['advance_cm'])};",
        '    constexpr float MantlePath[][2] = {' + ', '.join('{' + f(a) + ', ' + f(b) + '}' for a, b in mantle['capsule_path_cm_per_frame']) + '};',
        f"    constexpr int MantleFrames = {len(mantle['capsule_path_cm_per_frame']) - 1};",
        f"    constexpr float MantleRefStep = {f(mantle['reference_step_cm'])};",
        f"    constexpr float MantleAdvance = {f(mantle['advance_cm'])};",
        '    // Side jump: sideways launch at takeoff; the clip holds just before land while airborne.',
        f"    constexpr float SideTakeoff = {f(side['events_s']['takeoff'])};",
        f"    constexpr float SideLand = {f(side['events_s']['land'])};",
        f"    constexpr float SideLateralSpeed = {f(side['launch']['lateral_cm_s'])};",
        f"    constexpr float SideVerticalSpeed = {f(side['launch']['vertical_cm_s'])};",
        f"    constexpr FStance SideJumpStance{stance(side)};",
        '    // Side jump length follows the run latch (user 2026-09-29): short from a walk, long from a run.',
        f"    constexpr float SideShortLateralSpeed = {f(side['launch_walking']['lateral_cm_s'])};",
        f"    constexpr float SideShortVerticalSpeed = {f(side['launch_walking']['vertical_cm_s'])};",
        f"    constexpr float SideLongLateralSpeed = {f(side['launch_running']['lateral_cm_s'])};",
        f"    constexpr float SideLongVerticalSpeed = {f(side['launch_running']['vertical_cm_s'])};",
        '    // Strafe (sidestep / bounding shuffle): loop phase follows sideways travel over the stride.',
        f"    constexpr float StrafeSpeed = {f(strafe['reference_speed_cm_s'])};",
        f"    constexpr float StrafeStride = {f(strafe['stride_cycle_cm'])};",
        f"    constexpr float StrafeRunSpeed = {f(strafe_run['reference_speed_cm_s'])};",
        f"    constexpr float StrafeRunStride = {f(strafe_run['stride_cycle_cm'])};",
        f"    constexpr FStance StrafeLeftStance{stance(strafe)};",
        f"    constexpr FStance StrafeRightStance{stance(clips['StrafeRight'])};",
        f"    constexpr FStance StrafeRunLeftStance{stance(strafe_run)};",
        f"    constexpr FStance StrafeRunRightStance{stance(clips['StrafeRunRight'])};",
        '}',
        '',
    ]
    text = '\n'.join(lines)
    if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
        OUT.write_text(text, encoding='utf-8', newline='\n')
    print('CHUCK_CLIP_DATA', OUT.name, 'walk', walk['reference_speed_cm_s'], 'cm/s', walk['duration_s'], 's')


if __name__ == '__main__':
    main()
