"""Write Unreal/Chuck3D/Source/Chuck3D/ChuckClipData.h from the v1 clip manifest.

python Tools/gen_chuck_clip_data.py   (also run by Tools/build_chuck_v1.py)

The runtime (ChuckCharacter.cpp) distance-matches WalkStart/WalkLoop/WalkStop,
locks paws in the manifest stance windows and drives turn-in-place yaw from the
authored profile. Generating those numbers keeps the game in step with the
clips whenever the walk is re-authored (e.g. the 2026-09-27 saunter).
Pure Python; no Blender or Unreal needed.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / 'SourceAssets/Chuck/V1/Animations/manifest.json'
OUT = ROOT / 'Unreal/Chuck3D/Source/Chuck3D/ChuckClipData.h'


def f(v):
    return f'{v:.4f}f'


def stance(clip, mirror=False):
    """FStance initializer: up to three [lift, plant] spans per paw, -1 padded."""
    si = clip['stance_intervals_s']
    left, right = si['foot_L'], si['foot_R']
    if mirror:
        left, right = right, left
    def side(spans):
        flat = [v for span in spans for v in span][:6]
        flat += [-1.] * (6 - len(flat))
        return '{' + ', '.join(f(v) for v in flat) + '}'
    end = clip['duration_s']
    return f'{{{side(left)}, {side(right)}, {f(end)}}}'


def main():
    m = json.loads(MANIFEST.read_text(encoding='utf-8'))
    clips = {c['name']: c for c in m['clips']}
    walk, start, stop = clips['WalkLoop'], clips['WalkStart'], clips['WalkStop']
    turn = clips['TurnLeft90']
    yaw = [abs(v) for v in turn['capsule_yaw_deg_per_frame']]
    # Frames until the yaw reaches its final value; the tail is the settle hold.
    last = next(i for i, v in enumerate(yaw) if abs(v - yaw[-1]) < 1e-3)
    turn_end = max(t for k, t in turn['events_s'].items() if 'plant' in k) + .03
    lines = [
        '// Generated by Tools/gen_chuck_clip_data.py from',
        '// SourceAssets/Chuck/V1/Animations/manifest.json. Do not edit by hand.',
        '#pragma once',
        '',
        'namespace ChuckClipData',
        '{',
        '    // WalkLoop: distance-matched saunter (manifest reference speed, cycle, stance).',
        f"    constexpr float WalkSpeed = {f(walk['reference_speed_cm_s'])};",
        f"    constexpr float WalkPeriod = {f(walk['duration_s'])};",
        f"    constexpr float WalkStride = {f(walk['stride_cycle_cm'])};",
        f"    constexpr float StanceFraction = {f(walk['stance_fraction'])};",
        '    // WalkStart/WalkStop: smoothstep speed ramps over Duration covering Travel cm.',
        f"    constexpr float StartDuration = {f(start['duration_travel_s'])};",
        f"    constexpr float StartTravel = {f(start['travel_cm'])};",
        f"    constexpr float StopDuration = {f(stop['duration_travel_s'])};",
        f"    constexpr float StopTravel = {f(stop['travel_cm'])};",
        '',
        '    // Stance windows (s): foot_L spans, foot_R spans (lift/plant pairs, -1 padded), clip end.',
        '    struct FStance { float L[6]; float R[6]; float End; };',
        f"    constexpr FStance StartStance{stance(start)};",
        f"    constexpr FStance StopStance{stance(stop)};",
        f"    constexpr FStance StopStanceMirrored{stance(stop, True)};",
        f"    constexpr FStance TurnLeftStance{stance(turn)};",
        f"    constexpr FStance TurnRightStance{stance(clips['TurnRight90'])};",
        '',
        '    // Turn in place: capsule yaw magnitude (deg) per 30 fps frame until it settles.',
        '    constexpr float TurnYaw[] = {' + ', '.join(f(v) for v in yaw[:last + 1]) + '};',
        f'    constexpr int TurnYawFrames = {last};',
        f'    constexpr float TurnEnd = {f(turn_end)};  // just after the last plant',
        '}',
        '',
    ]
    text = '\n'.join(lines)
    if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
        OUT.write_text(text, encoding='utf-8', newline='\n')
    print('CHUCK_CLIP_DATA', OUT.name, 'walk', walk['reference_speed_cm_s'], 'cm/s', walk['duration_s'], 's')


if __name__ == '__main__':
    main()
